// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartShoppingAssistantLigaAc.DataAccess;

#nullable disable

namespace SmartShoppingAssistantLigaAc.DataAccess.Migrations
{
    [DbContext(typeof(SmartShoppingAssistantDbContext))]
    [Migration("20260615131555_RestrictCartItemProductDelete")]
    partial class RestrictCartItemProductDelete
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProductCategories", b =>
                {
                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.HasKey("CategoryId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            ProductId = 1
                        },
                        new
                        {
                            CategoryId = 1,
                            ProductId = 2
                        },
                        new
                        {
                            CategoryId = 1,
                            ProductId = 3
                        },
                        new
                        {
                            CategoryId = 2,
                            ProductId = 4
                        },
                        new
                        {
                            CategoryId = 2,
                            ProductId = 5
                        },
                        new
                        {
                            CategoryId = 2,
                            ProductId = 6
                        },
                        new
                        {
                            CategoryId = 3,
                            ProductId = 7
                        },
                        new
                        {
                            CategoryId = 3,
                            ProductId = 8
                        },
                        new
                        {
                            CategoryId = 3,
                            ProductId = 9
                        },
                        new
                        {
                            CategoryId = 4,
                            ProductId = 10
                        },
                        new
                        {
                            CategoryId = 4,
                            ProductId = 11
                        },
                        new
                        {
                            CategoryId = 4,
                            ProductId = 12
                        },
                        new
                        {
                            CategoryId = 5,
                            ProductId = 13
                        },
                        new
                        {
                            CategoryId = 5,
                            ProductId = 14
                        },
                        new
                        {
                            CategoryId = 5,
                            ProductId = 15
                        });
                });

            modelBuilder.Entity("SmartShoppingAssistantLigaAc.DataAccess.Entities.ActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ActorEmail")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int?>("ActorId")
                        .HasColumnType("integer");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.ToTable("ActivityLogs", (string)null);
                });

            modelBuilder.Entity("SmartShoppingAssistantLigaAc.DataAccess.Entities.Banner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LinkTo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("PromotionId")
                        .HasColumnType("integer");

                    b.Property<string>("Subtitle")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("PromotionId");

                    b.ToTable("Banners", (string)null);
                });

            modelBuilder.Entity("SmartShoppingAssistantLigaAc.DataAccess.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("CartItems", (string)null);
                });

            modelBuilder.Entity("SmartShoppingAssistantLigaAc.DataAccess.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Fresh fruits and berries",
                            Name = "Fruits"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Fresh vegetables and greens",
                            Name = "Vegetables"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Milk, cheese, yogurt and other dairy products",
                            Name = "Dairy"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Water, juices, soft drinks and more",
                            Name = "Beverages"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Chips, chocolate and light snacks",
                            Name = "Snacks"
                        });
                });

            modelBuilder.Entity("SmartShoppingAssistantLigaAc.DataAccess.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("PlacedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ShippingCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ShippingName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ShippingPhone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ShippingPostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Total")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlacedAt");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("SmartShoppingAssistantLigaAc.DataAccess.Entities.OrderAppliedPromotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Discount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("PromotionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("PromotionId");

                    b.ToTable("OrderAppliedPromotions", (string)null);
                });

            modelBuilder.Entity("SmartShoppingAssistantLigaAc.DataAccess.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("SmartShoppingAssistantLigaAc.DataAccess.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Banana",
                            Price = 3.99m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 2,
                            Name = "Apple",
                            Price = 5.99m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 3,
                            Name = "Orange",
                            Price = 4.49m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 4,
                            Name = "Carrot",
                            Price = 2.99m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 5,
                            Name = "Tomato",
                            Price = 6.99m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 6,
                            Name = "Spinach",
                            Price = 8.49m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 7,
                            Name = "Milk",
                            Price = 7.99m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 8,
                            Name = "Cheese",
                            Price = 24.99m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 9,
                            Name = "Yogurt",
                            Price = 5.49m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 10,
                            Name = "Orange Juice",
                            Price = 12.99m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 11,
                            Name = "Still Water",
                            Price = 3.49m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 12,
                            Name = "Cola",
                            Price = 8.99m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 13,
                            Name = "Chips",
                            Price = 9.99m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 14,
                            Name = "Chocolate Bar",
                            Price = 14.99m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 15,
                            Name = "Crackers",
                            Price = 7.49m,
                            StockQuantity = 100
                        });
                });

            modelBuilder.Entity("SmartShoppingAssistantLigaAc.DataAccess.Entities.Promotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Reward")
                        .HasColumnType("integer");

                    b.Property<int>("RewardValue")
                        .HasColumnType("integer");

                    b.Property<decimal>("Threshold")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProductId");

                    b.ToTable("Promotions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Banana Bundle Deal",
                            ProductId = 1,
                            Reward = 0,
                            RewardValue = 1,
                            Threshold = 3m,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            IsActive = true,
                            Name = "Fruit Basket Discount",
                            Reward = 1,
                            RewardValue = 10,
                            Threshold = 5m,
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            IsActive = true,
                            Name = "Dairy Combo Deal",
                            Reward = 0,
                            RewardValue = 1,
                            Threshold = 2m,
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Big Cart Discount",
                            Reward = 1,
                            RewardValue = 5,
                            Threshold = 100m,
                            Type = 1
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 4,
                            IsActive = true,
                            Name = "Beverage Bundle",
                            Reward = 1,
                            RewardValue = 15,
                            Threshold = 3m,
                            Type = 0
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 5,
                            IsActive = true,
                            Name = "Snack Attack",
                            Reward = 0,
                            RewardValue = 1,
                            Threshold = 4m,
                            Type = 0
                        });
                });

            modelBuilder.Entity("SmartShoppingAssistantLigaAc.DataAccess.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("SmartShoppingAssistantLigaAc.DataAccess.Entities.WishlistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId", "ProductId")
                        .IsUnique();

                    b.ToTable("WishlistItems", (string)null);
                });

            modelBuilder.Entity("ProductCategories", b =>
                {
                    b.HasOne("SmartShoppingAssistantLigaAc.DataAccess.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartShoppingAssistantLigaAc.DataAccess.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartShoppingAssistantLigaAc.DataAccess.Entities.Banner", b =>
                {
                    b.HasOne("SmartShoppingAssistantLigaAc.DataAccess.Entities.Promotion", "Promotion")
                        .WithMany()
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("SmartShoppingAssistantLigaAc.DataAccess.Entities.CartItem", b =>
                {
                    b.HasOne("SmartShoppingAssistantLigaAc.DataAccess.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartShoppingAssistantLigaAc.DataAccess.Entities.User", "User")
                        .WithMany("CartItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartShoppingAssistantLigaAc.DataAccess.Entities.Order", b =>
                {
                    b.HasOne("SmartShoppingAssistantLigaAc.DataAccess.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartShoppingAssistantLigaAc.DataAccess.Entities.OrderAppliedPromotion", b =>
                {
                    b.HasOne("SmartShoppingAssistantLigaAc.DataAccess.Entities.Order", "Order")
                        .WithMany("AppliedPromotions")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartShoppingAssistantLigaAc.DataAccess.Entities.Promotion", "Promotion")
                        .WithMany("OrderUsages")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("SmartShoppingAssistantLigaAc.DataAccess.Entities.OrderItem", b =>
                {
                    b.HasOne("SmartShoppingAssistantLigaAc.DataAccess.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("SmartShoppingAssistantLigaAc.DataAccess.Entities.Promotion", b =>
                {
                    b.HasOne("SmartShoppingAssistantLigaAc.DataAccess.Entities.Category", "Category")
                        .WithMany("Promotions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmartShoppingAssistantLigaAc.DataAccess.Entities.Product", "Product")
                        .WithMany("Promotions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SmartShoppingAssistantLigaAc.DataAccess.Entities.WishlistItem", b =>
                {
                    b.HasOne("SmartShoppingAssistantLigaAc.DataAccess.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartShoppingAssistantLigaAc.DataAccess.Entities.User", "User")
                        .WithMany("WishlistItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartShoppingAssistantLigaAc.DataAccess.Entities.Category", b =>
                {
                    b.Navigation("Promotions");
                });

            modelBuilder.Entity("SmartShoppingAssistantLigaAc.DataAccess.Entities.Order", b =>
                {
                    b.Navigation("AppliedPromotions");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("SmartShoppingAssistantLigaAc.DataAccess.Entities.Product", b =>
                {
                    b.Navigation("Promotions");
                });

            modelBuilder.Entity("SmartShoppingAssistantLigaAc.DataAccess.Entities.Promotion", b =>
                {
                    b.Navigation("OrderUsages");
                });

            modelBuilder.Entity("SmartShoppingAssistantLigaAc.DataAccess.Entities.User", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Orders");

                    b.Navigation("WishlistItems");
                });
#pragma warning restore 612, 618
        }
    }
}
